### ISSUE TITLE
Better Quiz App Question

### ISSUE THREAD

**Issue by jaehoonhwang** [starrodkirby86/better-quiz-app#9]
Is this software actually better than any quiz app out there?
Because the name of your app suggests better, but I don't know. 
It seems like calling it better sounds very arrogant. 
I would like you guys to fix this issue asap.
This is an easy problem to fix and I don't wanna feel arrogant when I use your software.

Thanks and have a very ~~dank~~ good day.

**Comment by starrodkirby86** [comment]
Is this issue actually better than any issues out there?
Because the way of your post suggests that, but I don't know.
It seems like calling us arrogant sounds very arrogant.
I would like you to fix your attitude asap.
This is an easy problem to fix and I don't want my jimmies rustled when I close this issue.

Thanks and have a very ~~good~~ dank day.
